title:       "Operating Systems 2021-2 (OS212)"
version:     "0001---31-Aug-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-13"
author:           "Abdul-Rahman"
address:          "Kendari"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://abdulrahman01uiacid.github.io/os212-1/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/abdulrahman01uiacid/os212-1/"
urlghpage:        "https://abdulrahman01uiacid.github.io/os212-1/"
keywords:         "jekyll, testing"
github:           
  - metadata

